/// Flutter icons Pix
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pix
///      fonts:
///       - asset: fonts/Pix.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Pix {
  Pix._();

  static const _kFontFam = 'Pix';
  static const String? _kFontPkg = null;

  static const IconData pix = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
